apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wklvxa2vn-nodejs
  janus-idp.io/tekton: wklvxa2vn-nodejs
  backstage.io/kubernetes-id: wklvxa2vn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wklvxa2vn-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
