apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wklvxa2vn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wklvxa2vn-nodejs 
  name: wklvxa2vn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wklvxa2vn-nodejs 
